### ISSUE TITLE
OSError: igzip: Error while decompressing extra concatenated gzip files

### ISSUE THREAD

**Issue by bakerwm** [pycompression/xopen#67]
> I know, I found a similar issue, (see [#26604](https://github.com/bioconda/bioconda-recipes/issues/26604) on cutadapt repo). 
it might be `xopen` issue, I think, so I post my problem here. 

I got the following error, when I use `cutadapt (version 3.2)` to process one of the Paired-end file (read2). It is fine, working on the other one (read1). (`xopen 1.1.0` return the same error).

What is wrong with the gzipped file?
My current solution is to unzip and gzip the file, it works.

### Using Cutadapt (for read2)

```bash
$ cutadapt --version
3.2

$ cutadapt -a AAAAAA Next_Ad2_15_raw_2.fq.gz -o a.fq.gz 1> a.log
[   8=-------] 00:00:09     1,838,760 reads  @      5.2 µs/read;  11.55 M reads/minuteTraceback (most recent call last):
  File "/data/yulab/wangming/miniconda3/envs/hiseq/bin/cutadapt", line 10, in <module>
    sys.exit(main_cli())
  File "/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/cutadapt/__main__.py", line 845, in main_cli
    main(sys.argv[1:])
  File "/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/cutadapt/__main__.py", line 912, in main
    stats = r.run()
  File "/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/cutadapt/pipeline.py", line 824, in run
    raise e
OSError: igzip: Error while decompressing extra concatenatedgzip files on Next_Ad2_15_raw_2.fq.gz (exit code 1)
```

### Using `xopen` package for read2

```python
$ file Next_Ad2_15_raw_2.fq.gz
Next_Ad2_15_raw_2.fq.gz: gzip compressed data, extra field, has comment, original size modulo 2^32 0

$ ipython
ln [3]: import xopen
In [4]: with xopen.xopen('Next_Ad2_15_raw_2.fq.gz') as f:
   ...:     for line in f:
   ...:         pass
   ...:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-04f9f45d5522> in <module>
      1 with xopen.xopen('Next_Ad2_15_raw_2.fq.gz') as f:
      2     for line in f:
----> 3         pass
      4

/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/xopen/__init__.py in __exit__(self, *exc_in
fo)
    139
    140     def __exit__(self, *exc_info):
--> 141         self.close()
    142
    143     def __del__(self):

/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/xopen/__init__.py in close(self)
    325         self.process.wait()
    326         self._file.close()
--> 327         self._raise_if_error(allow_sigterm=allow_sigterm)
    328         self._stderr.close()
    329

/data/yulab/wangming/miniconda3/envs/hiseq/lib/python3.8/site-packages/xopen/__init__.py in _raise_if_error(self,
allow_sigterm)
    348             self._file.close()
    349             self._stderr.close()
--> 350             raise OSError("{} (exit code {})".format(message, retcode))
    351
    352     def read(self, *args) -> AnyStr:

OSError: igzip: Error while decompressing extra concatenated gzip files on Next_Ad2_15_raw_2.fq.gz (exit code 1)
```

### re-gzip the file, everything is OK

```bash
$ gunzip -c Next_Ad2_15_raw_1.fq.gz | gzip -c > new.Next_Ad2_15_raw_1.fq.gz
$ gunzip -c Next_Ad2_15_raw_2.fq.gz | gzip -c > new.Next_Ad2_15_raw_2.fq.gz
$ ls -l *gz
-rw-r--r-- 1 wangming yulab 284848954 Jun 15 18:43 Next_Ad2_15_raw_1.fq.gz
-rw-r--r-- 1 wangming yulab 257515655 Jun 15 18:43 Next_Ad2_15_raw_2.fq.gz
-rw-r--r-- 1 wangming yulab 269179241 Jun 17 17:17 new.Next_Ad2_15_raw_1.fq.gz
-rw-r--r-- 1 wangming yulab 239088850 Jun 17 17:14 new.Next_Ad2_15_raw_2.fq.gz
# the new file is smaller in size

$ file *gz
Next_Ad2_15_raw_1.fq.gz:     gzip compressed data, extra field, has comment, original size modulo 2^32 0
Next_Ad2_15_raw_2.fq.gz:     gzip compressed data, extra field, has comment, original size modulo 2^32 0
new.Next_Ad2_15_raw_1.fq.gz: gzip compressed data, from Unix, original size modulo 2^32 651824910
new.Next_Ad2_15_raw_2.fq.gz: gzip compressed data, from Unix, original size modulo 2^32 651824910


$ ipython
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from xopen import xopen

In [2]: with xopen('new.Next_Ad2_15_raw_2.fq.gz') as f:
   ...:     for line in f:
   ...:         pass
   ...:

In [3]: with xopen('Next_Ad2_15_raw_1.fq.gz') as f:
   ...:     for line in f:
   ...:         pass
   ...:

In [4]: with xopen('new.Next_Ad2_15_raw_1.fq.gz') as f:
   ...:     for line in f:
   ...:         pass
   ...:

```

**Comment by marcelm** [comment]
The main discussion for this bug is over at https://github.com/marcelm/cutadapt/issues/513.

That thread is a bit long, so the short version: The gzip file contains multiple blocks (compressed separately). This isn’t handled correctly by older versions of `igzip`. You should update to the most recent version of the `isa-l` package. Try `conda update isa-l` and make sure that you get isa-l at version 2.30.0 or later, build `ha770c72_2` or later (`ha770c72_4` appears to be the current one).

**Comment by rhpvorderman** [comment]
@marcelm I made a PR on the conda feedstock to make sure 2.30.0 or higher is installed via conda in the future. https://github.com/conda-forge/xopen-feedstock/pull/17

**Comment by bakerwm** [comment]
@marcelm Thanks so much,  isa-l version `2.30.0`, build `ha770c72_4` works.
> by the way, The isa-l version `2.30.0`, build `h36c2ea0_0` not working.

**Comment by rhpvorderman** [comment]
Yes the older build of isa-l had issues. The newer build was provided to fix those issues.

**Comment by bakerwm** [comment]
Problem fixed, I will close this issue. Thanks @marcelm, @rhpvorderman
